name: Build and Deploy in Codespaces

# Trigger the workflow when you push to main branch
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t cicd-demo .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy locally in Codespaces
        run: |
          docker ps
          docker images
          # docker stop cicd_demo_app || true
          # docker rm cicd_demo_app || true
          docker run -d --name cicd_demo_app -p 3000:3000 cicd-demo
