
name: Build and Deploy Docker App to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4

      # - name: Log in to Docker Hub
      #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # - name: Build Docker image
      #   run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd-demo:latest .

      # - name: Push Docker image
      #   run: docker push ${{ secrets.DOCKER_USERNAME }}/cicd-demo:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'docker-app'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B7AB9D5F6CC148888EA37BFC933118DE }}
          images: ${{ secrets.DOCKER_USERNAME }}/cicd-demo:latest
